#!/bin/bash

#export DISPLAY=:0
XKBDIR=/tmp/xkb
mkdir -p ${XKBDIR}/{keymap,symbols,types}

# Generate a basic keymap.
setxkbmap -option -option caps:super -print \
    | sed 's/\(\s*xkb_symbols\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+custom(special)\2/g' \
    > ${XKBDIR}/keymap/custom.xkb

# Add customisations to its `xkb_symbols`. We assign Tab to some weird key so
# that `xcape` won't get confused. We use the ISO_Level3_Shift key for mode
# switching, because we can then just add our special keys as level 3 syms.
# Check out /usr/share/X11/xkb for codes and /usr/include/X11/keysymdef.h for
# symbols. Use `xev` for inspection.
tee > ${XKBDIR}/symbols/custom << EOF
default partial modifier_keys
partial
xkb_symbols "special" {

    modifier_map Mod4 { <LALT> };

    # Unused keys that must be present for xcape to work with
    key <I252> { [ Tab ] };
    key <I253> { [ Escape ] };
    key <I254> { [ ISO_Next_Group ] };

    key <RTSH> { [ Mode_switch ] };

    key  <TAB> { [ ISO_Level3_Shift ] };
    key <RALT> { [ Multi_key, dead_greek ] };

    #replace key <RALT> { [ ISO_Level3_Shift ] };
    #key <LALT> { [ Alt_L, Alt_L, Multi_key, dead_greek ] };

    key <LWIN> { [ Super_L, Escape ] };

    key <ESC>  { [ asciitilde, grave ] };
    key <BKSP> { [ BackSpace, BackSpace, Delete ] };
    key <SPCE> { [ space, space, BackSpace ] };
    key <AC11> { [ apostrophe, quotedbl, grave ] };

    key <AC01> { [ a, A, Left ], [Left, Home] };
    key <AC02> { [ s, S, Down ], [Down, Next] };
    key <AC03> { [ d, D, Right ], [Right, End]};
    key <AD01> { [ q, Q, BackSpace ], [BackSpace] };
    key <AD02> { [ w, W, Up ], [Up, Prior] };
    key <AD03> { [ e, E, Delete ], [Delete] };

    key <AE07> { [ 7, ampersand ], [7] };
    key <AE08> { [ 8, asterisk ], [8] };
    key <AE09> { [ 9, parenleft ], [9] };
    key <AE10> { [ 0, parenright ], [equal] };
    key <AD06> { [ y, Y ], [asterisk] };
    key <AD07> { [ u, U ], [4] };
    key <AD08> { [ i, I ], [5] };
    key <AD09> { [ o, O ], [6] };
    key <AD10> { [ p, P ], [slash] };
    key <AC06> { [ h, H, Left ], [plus]};
    key <AC07> { [ j, J, Down ], [1]};
    key <AC08> { [ k, K, Up ], [2] };
    key <AC09> { [ l, L, Right ], [3] };
    key <AC10> { [ semicolon, colon ], [minus]};
    key <AB06> { [ n, N ], [period] };
    key <AB07> { [ m, M ], [0] };
    key <AB08> { [ comma, less, Home ], [parenleft] };
    key <AB09> { [ period, greater, End ], [parenright] };
    key <AB10> { [ slash, question ], [backslash] };
};
EOF

# Compile the new xkbmap
xkbcomp -synch -w3 -I${XKBDIR} ${XKBDIR}/keymap/custom.xkb ${DISPLAY}

# (Re)start xcape, to make sure we can still use the original keys by tapping
# the respective modifiers.
pkill xcape
xcape -e 'Super_L=Escape;ISO_Level3_Shift=Tab;Mode_switch=ISO_Next_Group' -t 150ms
