#!/bin/bash
set -euo pipefail

# Find the keyboard IDs of the left and right parts of the R-Go Split keyboard
LEFT=$(xinput list | sed -n 's/.*HID 0911:2188\s\+id=\([0-9]\+\).*/\1/p')
RIGHT=$(xinput list | sed -n 's/.*Hantick USB Keyboard\s\+id=\([0-9]\+\).*/\1/p')

XKBDIR=/tmp/xkb
mkdir -p ${XKBDIR}/{keymap,symbols,types,compat}

setxkbmap -device $LEFT -option -print \
    | sed 's/\(\s*xkb_symbols\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+rgo(space)\2/g' \
    > ${XKBDIR}/keymap/rgo.xkb

tee > ${XKBDIR}/symbols/rgo << EOF
default partial modifier_keys
partial
xkb_symbols "space" {
    key <SPCE> { [ BackSpace ] };
};
EOF

xkbcomp -synch -w3 -I${XKBDIR} -i $LEFT ${XKBDIR}/keymap/rgo.xkb ${DISPLAY}
