#!/bin/bash

if [ -z "${DISPLAY}" ]; then
    echo "\$DISPLAY not set" >&2
    exit 1
fi

XKBDIR=/tmp/xkb
mkdir -p ${XKBDIR}/{keymap,symbols,types,compat}

# Generate a basic keymap.
setxkbmap -option -option caps:super -print \
    | sed 's/\(\s*xkb_symbols\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+thumbledore(td)\2/g' \
    > ${XKBDIR}/keymap/thumbledore.xkb

tee > ${XKBDIR}/symbols/thumbledore << EOF
default partial modifier_keys
partial
xkb_symbols "td" {

    # Modifier keys themselves
    replace key <LWIN> { [ Alt_L, Alt_R ] };
    replace key <LALT> { [ ISO_Level3_Shift, ISO_Level3_Shift ]};
    replace key <RALT> { [ ISO_Level3_Shift, ISO_Level3_Shift ], actions[Group1]=
        [ SetMods(mods=Shift+Mod5)
        , SetMods(mods=Shift+Mod5) ] };

    # Perhaps turn plain Return into menu key?
    key <RTRN> { [ Return, Return, equal, equal  ] };

    # Perhaps use tab key?
    key <RTSH> { [ Multi_key, dead_greek, dead_greek, dead_greek ] };

    key <AD01> { [ q, Q, Home, Home ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<HOME>, clearMods=Mod5+Shift) ] };
    key <AD02> { [ w, W, Up, Up ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<UP>, clearMods=Mod5+Shift) ] };
    key <AD03> { [ e, E, End, End ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<END>, clearMods=Mod5+Shift) ] };
    key <AD04> { [ r, R, Prior, Prior ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<PGUP>, clearMods=Mod5+Shift) ]
    };
    key <AD05> { [ t, T, numbersign, numbersign ] };
    key <AD06> { [ y, Y, at, at ] };
    key <AD07> { [ u, U, 7, 7 ] };
    key <AD08> { [ i, I, 8, 8 ] };
    key <AD09> { [ o, O, 9, 9 ] };
    key <AD10> { [ p, P, plus, plus ] };
    key <AD11> { [ bracketleft, braceleft, asciicircum, asciicircum ] };
    key <AD12> { [ bracketright, braceright, dollar, dollar ] };

    key <AC01> { [ a, A, Left, Left ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<LEFT>, clearMods=Mod5+Shift) ] };
    key <AC02> { [ s, S, Down, Down ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<DOWN>, clearMods=Mod5+Shift) ] };
    key <AC03> { [ d, D, Right, Right ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<RGHT>, clearMods=Mod5+Shift) ] };
    key <AC04> { [ f, F, Next, Next ], actions[Group1] =
        [ NoAction(), NoAction(), NoAction()
        , Redirect(key=<PGDN>, clearMods=Mod5+Shift) ] };
    key <AC05> { [ g, G, asciitilde, asciitilde ] };
    key <AC06> { [ h, H, asterisk, asterisk ] };
    key <AC07> { [ j, J, 4, 4 ] };
    key <AC08> { [ k, K, 5, 5 ] };
    key <AC09> { [ l, L, 6, 6 ] };
    key <AC10> { [ semicolon, colon, minus, minus ] };
    key <AC11> { [ apostrophe, quotedbl, grave, grave ] };

    key <AB01> { [ z, Z, bar, bar ] };
    key <AB02> { [ x, X, underscore, underscore ] };
    key <AB03> { [ c, C, parenleft, parenleft ] };
    key <AB04> { [ v, V, parenright, parenright ] };
    key <AB05> { [ b, B, ampersand, ampersand ] };
    key <AB06> { [ n, N, 0, 0 ] };
    key <AB07> { [ m, M, 1, 1 ] };
    key <AB08> { [ comma, less, 2, 2 ] };
    key <AB09> { [ period, greater, 3, 3 ] };
    key <AB10> { [ slash, question, exclam, exclam ] };

    # Thumb cluster
    key <SPCE> { [ space, space, BackSpace, Delete ], actions[Group1] = 
        [ NoAction()
        , Redirect(key=<SPCE>, clearMods=Shift)
        , Redirect(key=<BKSP>, clearMods=Mod5)
        , Redirect(key=<DELE>, clearMods=Mod5+Shift) ]
    };
};
EOF

# Compile the new xkbmap
xkbcomp -synch -w3 -I${XKBDIR} ${XKBDIR}/keymap/thumbledore.xkb ${DISPLAY}

# (Re)start xcape, to make sure we can still use the original keys by tapping
# the respective modifiers.
pkill xcape
xcape -e 'Super_L=Escape;ISO_Level3_Shift=Return' -t 150ms
