#!/bin/bash

if [ -z "${DISPLAY}" ]; then
    echo "\$DISPLAY not set" >&2
    exit 1
fi

XKBDIR=/tmp/xkb
mkdir -p ${XKBDIR}/{keymap,symbols,types,compat}

# Generate a basic keymap.
setxkbmap -option -option caps:super -print \
    | sed 's/\(\s*xkb_symbols\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+custom(special)\2/g' \
    | sed 's/\(\s*xkb_types\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+custom(special)\2/g' \
    | sed 's/\(\s*xkb_compat\s*{\s*include\s*".*\)\("\s*};\s*\)/\1+custom(special)\2/g' \
    > ${XKBDIR}/keymap/custom.xkb

# Generate compatibility map
tee > ${XKBDIR}/compat/custom << EOF
xkb_compatibility "special" {
   interpret Hyper_L { action= SetMods(modifiers=Mod3); };
   interpret Hyper_R { action= SetMods(modifiers=Mod5); };
};
EOF

# Generate type map
tee > ${XKBDIR}/types/custom << EOF
default xkb_types "special" {

    type "NONE_SHIFT_LALT_RALT" {

        modifiers = Shift+Mod3+Mod5;
        map[None] = Level1;
        map[Shift] = Level2;
        map[Mod3] = Level3;
        map[Mod3+Shift] = Level3;
        map[Mod5] = Level4;
        map[Mod5+Shift] = Level4;
        map[Mod5+Mod3] = Level4;
        map[Mod5+Mod3+Shift] = Level4;

        preserve[Mod3] = Mod3;
        preserve[Mod3+Shift] = Mod3+Shift;
        preserve[Mod5+Shift] = Shift;
        preserve[Mod5+Mod3] = Mod3;
        preserve[Mod5+Mod3+Shift] = Mod3+Shift;

        level_name[Level1] = "Base";
        level_name[Level2] = "Shift";
        level_name[Level3] = "Alt_L";
        level_name[Level4] = "Alt_R";
    };
};
EOF


# Add customisations to its `xkb_symbols`. We assign Tab to some weird key so
# that `xcape` won't get confused. We use the ISO_Level3_Shift key for mode
# switching, because we can then just add our special keys as level 3 syms.
# Check out /usr/share/X11/xkb for codes and /usr/include/X11/keysymdef.h for
# symbols. Use `xev` for inspection. Use `xmodmap` to see which modifiers are
# bound to which keys.
tee > ${XKBDIR}/symbols/custom << EOF
default partial modifier_keys
partial
xkb_symbols "special" {

    # Modifier keys themselves
    key <LWIN> { [ Alt_L ] };
    key <LALT> { [ Hyper_L ] };
    key <RALT> { [ Hyper_R ] };

    modifier_map Mod1 { Alt_L };
    modifier_map Mod3 { Hyper_L };
    # modifier_map Mod4 { Super_L };
    modifier_map Mod5 { Hyper_R };

    key.type[Group1] = "NONE_SHIFT_LALT_RALT";

    key <RTRN> { [ Return, Return, Multi_key, dead_greek ] };

    # Thumb cluster
    key <SPCE> { [ space, space, BackSpace, Delete ] };

    # Arrow block
    key <AC01> { [ a, A, Left, Home ] };
    key <AC03> { [ d, D, Right, End ] };
    key <AD02> { [ w, W, Up, Prior ] };
    key <AC02> { [ s, S, Down, Next ] };

    # Numpad
    key <AE07> { [ 7, ampersand, 7, 7] };
    key <AE08> { [ 8, asterisk , 8, 8] };
    key <AE09> { [ 9, parenleft, 9, 9] };
    key <AE10> { [ 0, parenright, equal, equal] };
    key <AD06> { [ y, Y, asterisk, asterisk] };
    key <AD07> { [ u, U, 4, 4] };
    key <AD08> { [ i, I, 5, 5] };
    key <AD09> { [ o, O, 6, 6] };
    key <AD10> { [ p, P, slash, slash] };
    key <AC06> { [ h, H, plus, plus]};
    key <AC07> { [ j, J, 1, 1]};
    key <AC08> { [ k, K, 2, 2] };
    key <AC09> { [ l, L, 3, 3] };
    key <AC10> { [ semicolon, colon, minus, minus]};
    key <AC11> { [ apostrophe, quotedbl, grave, grave ] };
    key <AB06> { [ n, N, period, period] };
    key <AB07> { [ m, M, 0, 0] };
    key <AB08> { [ comma, less, parenleft, parenleft] };
    key <AB09> { [ period, greater, parenright, parenright] };
    key <AB10> { [ slash, question, backslash, backslash] };
};
EOF

# Compile the new xkbmap
xkbcomp -synch -w3 -I${XKBDIR} ${XKBDIR}/keymap/custom.xkb ${DISPLAY}

# (Re)start xcape, to make sure we can still use the original keys by tapping
# the respective modifiers.
pkill xcape
xcape -e 'Super_L=Escape;Hyper_L=Return;Hyper_R=Return' -t 150ms
